### ISSUE TITLE
Ability to choose the update interval

### ISSUE THREAD

**Issue by barleybobs** [Limych/ha-car_wash#10]
**Is your feature request related to a problem? Please describe.**

I would like my car wash sensor to update hourly.

**Describe the solution you'd like**

I would like to be able to in my configuration.yaml setup how often the sensor updates. Similar to how if you set up a binary ping sensor you can define a 'scan_interval'

**Describe alternatives you've considered**

I have not found any alternative to this addon and have had a look at the code but do not understand enough to modify it for my needs.

**Comment by Limych** [comment]
It makes no sense to add an update period to this sensor.  The sensor state is recalculated as soon as the weather forecast data changes.

If you need more frequent updates of this sensor, simply increase the update rate of the weather forecast sensor.
