### ISSUE TITLE
The method for providing platform translations has changed in Home Assistant Core

### ISSUE THREAD

**Issue by emontnemery** [Limych/ha-car_wash#129]
The method for providing platform translations has changed in Home Assistant Core, and this integration needs to be updated.

Details can be found in https://developers.home-assistant.io/blog/2024/03/05/platform_entity_translations_deprecation

**Comment by Limych** [comment]
Thank you for your attention to the project. The change in how localizations are stored that you refer to only applies to Home Assistant Core components. Custom components store localizations the old fashioned way.

See more: https://developers.home-assistant.io/docs/internationalization/custom_integration
