### ISSUE TITLE
Add German Translation

### ISSUE THREAD

**Issue by LuckyTriple7** [Limych/ha-car_wash#27]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

German Translation
binary_sensor.de.json

**Describe alternatives you've considered**

{
  "state": {
    "car_wash__": {
      "off": "nicht empfehlenswert",
      "on": "guter Zeitpunkt"
    }
  }
}

**Additional context**

**Comment by Limych** [comment]
Please, open pull request with this translation.

And I believe that it would be more correct if the first letter in the statuses is capitalized. Although I do not know the rules of your language, I have no right to insist.

**Comment by LuckyTriple7** [comment]
Merged :-) Thank you very much.
