### ISSUE TITLE
TypeError: 'datetime.datetime' object is not subscriptable

### ISSUE THREAD

**Issue by peetereczek** [Limych/ha-car_wash#4]
**Version of the custom_component**
37d4419

**Configuration**
```yaml

binary_sensor:
  - platform: car_wash
    weather: weather.budapest

```

**Description**

Seems that script is not working. Take a look on below stack, is there anything I should change?
Latest version of Home Assistant 0.104.3

**Debug log**

```text

Wed Jan 29 2020 20:40:03 GMT+0100
Update for binary_sensor.car_wash fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 459, in async_device_update
    await self.async_update()
  File "/config/custom_components/car_wash/binary_sensor.py", line 165, in async_update
    fc_date = fc_date[:10]
TypeError: 'datetime.datetime' object is not subscriptable

```

**Comment by Limych** [comment]
The reason here is not in the sensor bug, but in the fact that your weather provider sends data in a non-standard format.
Please specify what weather provider you use - I will try to add a code to the sensor that corrects this bug of your provider.

**Comment by peetereczek** [comment]
I haven't changed weather provider since installation. I'm using met.no https://www.home-assistant.io/integrations/met/

**Comment by peetereczek** [comment]
Fixed, thanks!

And even weather is good to wash the car ;)
![image](https://user-images.githubusercontent.com/42431204/73450292-609ed000-4365-11ea-90ec-5e22f34ce3e3.png)
