### ISSUE TITLE
state_color setting

### ISSUE THREAD

**Issue by peetereczek** [Limych/ha-car_wash#5]
**Is your feature request related to a problem? Please describe.**

After HA update to version 0.105 icons are by default in only one color and don't react to sensor state. I liked when icon changed it's color, so could you consider bringing icon color feature when the state is on?

**Describe the solution you'd like**

Maybe we can set up in settings which color we want when we should wash the car? Or at least please bring back yellow color

**Describe alternatives you've considered**

I have tried overriding state_color attribute to "true" in customization, but no effect. Maybe you know simple solution?

**Additional context**

![image](https://user-images.githubusercontent.com/42431204/74134320-a02dad80-4bea-11ea-8eac-8a2d23e093c4.png)
State has no 'soul' anymore :(

**Comment by Limych** [comment]
The logic of the sensor has nothing to do with icon colors. It would be more correct to manage icon colors from the frontend. Therefore, excuse me, I am closing this issue.
