### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by jangelgon** [Limych/ha-car_wash#78]
**Is your feature request related to a problem? Please describe.**

 Is not a problem i suggest a spanish translation

**Describe the solution you'd like**

{
  "state": {
    "car_wash__": {
      "off": "No deberías Lavarlo",
      "on": "Merece la pena Lavarlo"
    }
  }
}

**Describe alternatives you've considered**

**Additional context**

**Comment by Limych** [comment]
Please file this as a pull request.

**Comment by Limych** [comment]
It was not entirely correct to close this issue before the PR was merged to the main branch.  Moreover, at the moment of closing the PR, the automation would also close the issue.
